site_name: Plutus Project Based Learning
site_url: https://gimbalabs.com/
nav: 
    - Getting started:
        - Introduction: index.md
        - Set up: setup.md
    - Projects:
        - Gift contract: projects/gift.md
        - Parametrized-Piggy-Bank: projects/param-pb-pab.md
        - Simple-NFT-Minter: projects/simple-nft-minter.md
        - NFT based Authentication: projects/auth.md
        - Wallet probe: projects/walletprobe.md
        - Loyalty tokens: projects/loyaltytokens.md
        - Applied Escrow: projects/appliedEscrow.md
    - Useful:
        - Interacting with the Blockchain: useful/interacting.md
        - Additional links: useful/links.md

theme: readthedocs
