site_name: Plutus Project Based Learning
site_url: https://gimbalabs.com/
nav: 
    - Home: index.md
    - Gift: gift.md
    - Parametrised-Piggy-Bank: param-pb-pab.md
    - Minting NFTs: mintingNFTs.md
    - NFT based Authentication: auth.md
    - Wallet probe: walletprobe.md
    - Loyalty tokens: loyaltytokens.md
theme: readthedocs
