site_name: Plutus Project Based Learning
site_url: https://gimbalabs.com/
nav: 
    - Introduction: index.md
    - Set up: setup.md
    - Gift: gift.md
    - Parametrised-Piggy-Bank: param-pb-pab.md
    - Simple-NFT-Minter: simple-nft-minter.md
    - NFT based Authentication: auth.md
    - Wallet probe: walletprobe.md
    - Loyalty tokens: loyaltytokens.md

theme: readthedocs
