site_name: Plutus Project Based Learning
site_url: https://gimbalabs.com/
nav: 
    - Getting started:
        - Introduction: index.md
        - Set up: setup.md
    - Projects:
        - Gift: projects/gift.md
        - Parametrized-Piggy-Bank: projects/param-pb-pab.md
        - Simple-NFT-Minter: projects/simple-nft-minter.md
        - NFT based Authentication: projects/auth.md
        - Wallet probe: projects/walletprobe.md
        - Loyalty tokens: projectsprojects/loyaltytokens.md
    - Useful:
        - Debugging: debugging.md
        - Testing: testing.md

theme: readthedocs
